version: 1

database:
  host: "localhost"
  port: "5432"
  username: "ZmFpdA=="
#  username: "fait"

  password: "RmFpdDIwMjQhIQ=="
#  password: "Fait2024!!"

  name: "dGVzdDU="
#  name: "test5"

  # DATABASE_URL = "postgresql://fait:Fait2024!!@localhost:5432/test5"
  #  postgresql://[username]:[password]@[host]:[port]/[database]




